# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ origin ]
  pull_request:
    branches: [ origin ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt && echo "install requirements..."; fi
        
    - name: Generate pages
      run: |
        echo 'Building site 👷 '
        pelican content -o output -s ${PELICAN_CONFIG_FILE:=pelicanconf.py}
    - name: Push content
      run: |
        remote_repo="https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git"
        remote_branch=${GH_PAGES_BRANCH:=gh-pages}
        
        echo 'Publishing to GitHub Pages 📤 '
        pushd output
        git init

        git remote add deploy "$remote_repo"
        git checkout $remote_branch || git checkout --orphan $remote_branch
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

        git add .

        echo -n 'Files to Commit:' && ls -l | wc -l
        git commit -m "[ci skip] Automated deployment to GitHub Pages on $(date +%s%3N)"
        git push deploy $remote_branch --force
        rm -fr .git
        popd
  
        echo '=================== Done  ==================='